# Generated by Django 6.0.4 on 2026-04-21 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordermodel",
            old_name="oder_id",
            new_name="order_id",
        ),
    ]
